#!/usr/bin/env python3
"""Generate assets/tailwind.css, replacing the Tailwind Play CDN at runtime.

    python3 tools/build-tailwind-css.py

Rather than shell out to the Tailwind CLI, this drives the *same* Play CDN build the
site runs today (pinned 3.4.17) and captures what it emits. That makes the compiled
file byte-for-byte the CSS the browser is already applying, so swapping the CDN <script>
for a <link> cannot change specificity, emission order, or Preflight behaviour.

How it works: every class-ish token in *.html and site.js is pasted into one hidden
element on a scratch page, the CDN's JIT compiles them, and the page POSTs the
generated stylesheet back to this script's own server, which writes it to disk.

IMPORTANT — where the <link> goes. The CDN injects its <style> AFTER each page's inline
<style>, so Tailwind utilities currently win ties against the page's own CSS (measured:
`.section-lead{font-size:19px}` loses to `text-2xl`). The <link> must therefore sit at
the END of <head>, after the inline <style>, or every such tie silently flips.

Equivalent if you have the standalone CLI instead:
    tailwindcss-3.4.17 -c tailwind.config.js -i tools/tailwind-src.css -o assets/tailwind.css --minify
"""
import http.server, os, re, socketserver, subprocess, sys, tempfile, threading, time, shutil

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
os.chdir(ROOT)
PORT = 4401
OUT = 'assets/tailwind.css'
CHROME = '/Applications/Google Chrome.app/Contents/MacOS/Google Chrome'
SOURCES = ['rdrp.html', 'bde.html', 'parents.html', 'yeatman.html', 'site.js']

# Tailwind's real extractor is a broad regex over the ENTIRE raw file text, not just
# class="..." attributes — and that matters here. site.js sets classes three different
# ways: inside class="..." templates, via el.className = '...' (line ~292, which is the
# only place `-mx-2` appears), and via classList calls. A scanner that only reads
# class="..." silently drops the others, and the missing utilities do not fail loudly —
# they just quietly change the layout. So mirror Tailwind: tokenize everything and let
# the JIT discard whatever is not a real utility. Over-generating costs a few KB; under-
# generating costs a broken page.
CANDIDATE = re.compile(r'[-A-Za-z0-9_:./\[\]#()%!,]{2,80}')

def collect_tokens():
    toks = set()
    for f in SOURCES:
        text = open(f, encoding='utf-8').read()
        for t in CANDIDATE.findall(text):
            if any(c.isalpha() for c in t):
                toks.add(t)
    return sorted(toks)

saved = {}

class Handler(http.server.SimpleHTTPRequestHandler):
    def log_message(self, *a):
        pass
    def do_POST(self):
        n = int(self.headers.get('Content-Length', 0))
        saved['css'] = self.rfile.read(n).decode('utf-8')
        self.send_response(204); self.end_headers()

def main():
    tokens = collect_tokens()
    print('  scanned %d files, %d distinct class tokens' % (len(SOURCES), len(tokens)))

    cfg = ("tailwind.config = { theme: { extend: { fontFamily: {"
           " serif: ['\"Source Serif 4\"', 'serif'],"
           " sans: ['\"Source Sans 3\"', 'sans-serif'], } } } };")
    page = (
        '<!DOCTYPE html><html><head><meta charset="utf-8">\n'
        '<script src="https://cdn.tailwindcss.com/3.4.17"></script>\n'
        '<script>%s</script>\n</head><body>\n'
        '<div class="%s"></div>\n<script>\n'
        'window.addEventListener("load", function(){ setTimeout(function(){\n'
        '  var css="";\n'
        '  for (var i=0;i<document.styleSheets.length;i++){\n'
        '    var s=document.styleSheets[i];\n'
        '    if (s.ownerNode && s.ownerNode.tagName==="STYLE" && s.cssRules.length>50){\n'
        '      css=s.ownerNode.textContent; }\n'
        '  }\n'
        '  fetch("/save",{method:"POST",body:css});\n'
        '}, 1200); });\n'
        '</script></body></html>' % (cfg, ' '.join(tokens))
    )
    scratch = '_tw_capture.html'
    open(scratch, 'w', encoding='utf-8').write(page)

    socketserver.TCPServer.allow_reuse_address = True
    srv = socketserver.TCPServer(('127.0.0.1', PORT), Handler)
    threading.Thread(target=srv.serve_forever, daemon=True).start()

    prof = tempfile.mkdtemp()
    p = subprocess.Popen([CHROME, '--headless=new', '--disable-gpu', '--no-sandbox',
        '--virtual-time-budget=20000', '--user-data-dir=' + prof,
        'http://127.0.0.1:%d/%s' % (PORT, scratch)],
        stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL)
    for _ in range(60):
        if 'css' in saved:
            break
        time.sleep(1)
    p.kill(); srv.shutdown()
    os.remove(scratch); shutil.rmtree(prof, ignore_errors=True)

    if 'css' not in saved or len(saved['css']) < 5000:
        print('  FAILED: captured %d bytes' % len(saved.get('css', '')))
        return 1
    header = ('/* Generated by tools/build-tailwind-css.py from the Tailwind 3.4.17\n'
              '   Play CDN build. Do not edit by hand. Re-run that script after adding\n'
              '   or removing any Tailwind class in *.html or site.js.\n'
              '   This <link> must load AFTER each page\'s inline <style>. */\n')
    open(OUT, 'w', encoding='utf-8').write(header + saved['css'].strip() + '\n')
    print('  wrote %s  (%.1f KB)' % (OUT, os.path.getsize(OUT) / 1024))
    return 0

sys.exit(main())
